### PR TITLE
Upload Wasm size report as workflow artifact.

### PR DESCRIPTION
**Pull request by whiten**

### CODE REVIEW

**Comment by aboodman** [comment]
Neat. Where does it show up, visually?

**Comment by whiten** [comment]
> Neat. Where does it show up, visually?

Not anywhere useful yet! Iterating on this. Here's where it is right now: https://github.com/rocicorp/repc/actions/runs/162498395

**Comment by whiten** [comment]
Shoot, I can't figure out how to put it anywhere useful yet. Currently it's available for download at the Artifacts link at https://github.com/rocicorp/repc/pull/33/checks.

I'm just going to push this for now and we can move it somewhere better as we learn more about GitHub workflows.

**Comment by aboodman** [comment]
It would be cool to also upload the compressed size which is more what we care about.

**Pull request merged**
