### PR TITLE
smol is dead code and

### PR DESCRIPTION
**Pull request by arv**

### CODE REVIEW

**Comment by arv** [comment]
I assume the idea was to use this in a test but it is not used in any test

**Comment by arv** [comment]
@whiten Where does the **Rust / Wasm Size** go?

**Comment by aboodman** [comment]
Oh yeah I guess I was thinking I'd use it in a test and then didn't. Thanks.

**Comment by whiten** [comment]
> @whiten Where does the **Rust / Wasm Size** go?

@arv, look for the "Artifacts" link at https://github.com/rocicorp/repc/pull/40/checks. (I wish I knew how to put it somewhere better.)

**Pull request merged**
