### PR TITLE
Use binary search for has and get

### PR DESCRIPTION
**Pull request by arv**
First look in the pending, then binary search the flatbuffers::Vector.

The std binary_search does not work on flatbuffers::Vector (at least I
could not figure out how to do it without a copy) so I copied and
modified the code.

### CODE REVIEW

**Comment by arv** [comment]
Got side tracked... but I had some fun!

**Comment by aboodman** [comment]
Nice but I kind of go back and forth on this. Once we have prolly trees then we should only have a small number of items in each node. So due to cpu caching I would be surprised if this makes it any faster or could even make it worse. It also increases complexity significantly

I kinda feel like in Rust we want to conserve our complexity budget wherever we can 😬. @phritz ?

**Comment by phritz** [comment]
Generally in favor of less complexity in rust. In this case seems like it should improve performance for now and the complexity is at least concentrated and doesn't have to be understood to use the thingy, so in favor of merging this.

**Comment by aboodman** [comment]
OK, LGTM then

**Pull request merged**
